### ISSUE TITLE
Allow DOMDocument usage

### ISSUE THREAD

**Issue by g105b** [phpgt/csrf#11]
I was working on a legacy project for a client that uses the DOMDocument to render the HTML. Using this repo on that project would involve rendering the DOMDocument into a HTMLDocument, then back again.

A few more type checks on `$html` in the HTMLDocumentProtector's constructor will be beneficial.

**Comment by j4m3s** [comment]
I did look into that actually - even wrote a test for it.  Then it failed and I concluded that the best solution would be to update the phpgt `HtmlDocument` constructor to accept a `DomDocument`.  Otherwise this module needs to start worrying about what type of Document it is whenever it needs to interact with it.

**Comment by g105b** [comment]
That's a much better idea.

**Comment by g105b** [comment]
See phpgt/dom#25
