### ISSUE TITLE
Inappropriate copyright notice?

### ISSUE THREAD

**Issue by j4m3s** [phpgt/csrf#8]
As an open source project I don't think it's right to mark code as copyright Brightflair Ltd - that's simply not the case for code written by others and will discourage contributions :)

**Comment by g105b** [comment]
I changed to to match the others, as I assumed wrong to have you or me in there personally. What do you think it should say?

**Comment by j4m3s** [comment]
I think there are two different questions:
  1. The copyright statement in the license file should be the author of the license text itself shouldn't it?  See https://github.com/drupal/drupal/blob/8.1.x/core/LICENSE.txt for example, the copyright of the text in the license file is the author of the license wording.
  2. The copyright statement for an individual file belongs to the author of the file, unless they explicitly transfer ownership elsewhere.  

Are you asking anyone that contributes code to php.gt to transfer the ownership of the copyright to Brightflair Ltd?

**Comment by g105b** [comment]
I don't really understand copyright for open source projects. Could the license file simply say "copyright all the contributors of this project"? Or do you think the original author who created the repo should get all copyright? I picked Bright Flair Ltd because that entity will have main responsibility for the project's management and support going forwards, but I understand that this isn't necessarily the same as owning the rights to a project.

**Comment by j4m3s** [comment]
I suspect the copyright statement is a waste of time.  Copyright is
implicit and automatic. And whoever the copyright owner is, the MIT license
makes clear what people are allowed to do with it anyway.

**Comment by g105b** [comment]
The copyright line is an automatic template from Github, so I'll just get rid of that as it is meaningless.
